# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: wtodoserver CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted
    env: 
      working-directory: /home/warren/wtodoserver

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: build website
      run: \[ -d wtodoserver/.git \] && cd wtodoserver && git reset --hard && git pull || git clone  git@github.com:vietvho/wtodoserver.git wtodoserver
      working-directory: /home/warren
    - name: compile
      working-directory: ${{ env.working-directory }}
      run: git checkout main
    - run: npm install yarn
      working-directory: ${{ env.working-directory }}
    - run: yarn install
      working-directory: ${{ env.working-directory }}
    - run: yarn upgrade
      working-directory: ${{ env.working-directory }}
    -  run: yarn start
      working-directory: ${{ env.working-directory }}
