# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: wtodoserver CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    # - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: build website
      run: \[ -d wtodoserver/.git \] && cd wtodoserver && git reset --hard && git pull || git clone  git@github.com:vietvho/wtodoserver.git wtodoserver
      working-directory: /home/warren
    - run: git checkout main
      working-directory: /home/warren/wtodoserver
    - run: npm install yarn
      working-directory: /home/warren/wtodoserver
    - run: yarn install
      working-directory: /home/warren/wtodoserver
    - run: yarn upgrade
      working-directory: /home/warren/wtodoserver
    - run: yarn start  & yarn wait-on http://api.wtodo.ga
      working-directory: /home/warren/wtodoserver
